### ISSUE TITLE
Issues with genPriorNetwork

### ISSUE THREAD

**Issue by wuwei77lx** [Roy-lab/scMTNI#10]
hello，
I have encountered a reference to the motif files in your GitHub script. I understand that the original motif files need to be obtained from you directly. May I kindly request access to these motif files for both human and mouse genomes?I would like to know if you have motifs available for the hg19 human genome assembly, and if there are motifs for hg38 as well. 
Furthermore, if there is any associated code or script that facilitates the retrieval of these motif files, it would be immensely helpful if you could share that with me.In addition, what is the difference between your bedtools and general bedtools, and why did the peak change after running the example, or was it just because some data was provided.
thanks

**Comment by shiluzhang** [comment]
Hi,
Thanks for your interest in scMTNI. The motif files for human and mouse have been uploaded to https://zenodo.org/record/8323399#.ZPlrKuzMLOE. To generate these motif files, we obtained sequence-specific motifs from the Cis-BP database (http://cisbp.ccbr.utoronto.ca/) and used the PIQ toolkit to identify significant motif instances genome-wide using the human genome assembly hg19 and mouse genome assembly mm10 respectively. We don't have motifs for hg38. If you need the motifs for hg38, you could consider applying liftOver to convert from hg19 to hg38.

The bedtools is the same as the general bedtools. The peak data and motif data in the ExampleData/ contain only a subset of the original files due to the file size limit in Github. So it would not be the same as the final prior networks cluster*_network.txt if you run the example.
