### ISSUE TITLE
Some questions about the input data for scMTNI

### ISSUE THREAD

**Issue by jingkun12137** [Roy-lab/scMTNI#12]
My data was on scRNA-seq and scATAC-seq on a group of mouse ILC cells. Following Shilu Zhang's method on github, I used liger to get the clustering results of the cells, but there were some issues that prevented me from proceeding.

1. I'm not sure how ExampleData/cluster*.table is obtained 

2. Should cluster*_allGenes.txt and cluster*_allregulators manually input some interested gene and regulators, or is there any way to get them quickly 

3. What I am interested in is only the influence of regulators on genes in ILC cells. Do I still need to construct a cell lineage tree

**Comment by SuvojitHazra** [comment]
Hello Jingkun Yi,

Thank you for your interest in scMTNI.

(1) As you asked, I would like to answer your third question first. scMTNI is a multi-task learning GRN (gene regulatory network) inference approach that always takes cell-lineage tree, scRNA-seq expression and/or scATAC-seq data as inputs to infer GRN for each cell-type on a cell-lineage. Therefore, you always need to construct a cell-lineage as you already have scRNA-seq expression and scATAC-seq data on a group of mouse ILC cells.

(2) Now coming to your first query, you have to make a data folder 'ExampleData' in your working directory, then, you have to put cell-type specific table files i.e., cluster*.table. Frankly speaking, you do not have to exactly follow the naming of these files, however, following the standard is always best. Otherwise, you can make text files like cluster*.txt or celltype*_expression.txt etc. inside the 'ExampleData' folder where, you have the matrix (gene x cell) information of scRNA-seq data for each cell cluster/celltype from you cell lineage tree. See https://github.com/Roy-lab/scMTNI for more details.

(3) For your second query, no shortcut or quick cheat code is there to generate cell-type/cluster specific cluster*_allGenes.txt and cluster*_allregulators.txt files. You specifically have to follow the step regarding running of the script namely, '**PreparescMTNIinputfiles.py**' of https://github.com/Roy-lab/scMTNI tutorial.

Kindly write us if you have any more queries. 

Cheers,
Suvojit.


Please cite this if you use scMTNI: Zhang, S., Pyne, S., Pietrzak, S., Halberg, S., McCalla, S.G., Siahpirani, A.F., Sridharan, R. and Roy, S., Inference of cell type-specific gene regulatory networks on cell lineages from single cell omic datasets. Nat Commun 14, 3064 (2023). https://doi.org/10.1038/s41467-023-38637-9
